on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: "24.2"
          elixir-version: "1.13.1"

      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-v1-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-v1-

      - name: Install dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test
